language: ruby
jobs:
  include:
  - stage: test
    name: "Unit tests"
    install:
    - gem install rspec
    script:
    - echo "Running tests against $(ruby -v)..."
    - rspec spec
  - name: "Integration tests"
    install:
    - gem build wash.gemspec
    - gem install wash-*.gem
    before_script:
    - curl -sfL https://github.com/puppetlabs/wash/releases/download/0.17.0/wash-0.17.0-x86_64-unknown-linux.tgz | tar -xz
    script:
    - ./wash validate examples/mock_docker.rb
  - stage: gem release
    name: "Deploy to RubyGems"
    script: echo "Deploying to rubygems.org..."
    deploy:
      provider: rubygems
      api_key:
        secure: MAkog8JPxT/qKuxKPGpWVtgsBdThIobKDLvAOMuMk73s2cykZSMilOav+jynJ3e8ELzDFBegaFgpcSzuPOsFOHzVAoRd0FSnin36kdNZsRZaDEwhr9Zn0bCOGf/EiZt48htrGF4dXz8gZkLR3Aur0shdhSk5kH3akfxWV4HiBf5V7ahFEuhpDeU4zYmaON6IQ0SBAu7c+s08XydXsOkHy3mqMGwXQVAwqyA4mCYp2xlllGRaNHxhDQUHLBPmJEHWpxrgACfRFev+4T/Un24ws3B1khxBILeW+gwjRzpW2cDReamiD0HfEPdNPbf2cXxqiJbXKmuMoL1NEjkH9YoLNokpK5ArE4m05uJw5++SLbNKAH6jV19Zjd7KBkR6z4z2wwvLWAbKI9Ah+uIMVYw70WTfVmgRoON3b7ELehnTUOy+BP3M62aQHC4bQo2W9GI4ERUb/Uz88t75xo25ZzQRFNCC3TG6xLD6Jetb7Btgj64F7YtfoJN0SbZ23Z9eStfX5cbLvJcOPXngAL0rAWwiXKp/QfQLH3DQ7e/bPwyLJ04PgWhA5uQfKNUDE2jlLI0YFZd879O52ocIknmvqXtop6RjTk5n9iEr++faitiih5/0aJ1yWaunekNW0dinzRoAlHSuw7xRZoEKgHJBPqjtClfiqdmhGxiAYJP+5pbCW1U=
      gem: wash
      on:
        repo: puppetlabs/wash-ruby
        tags: true
